#define	LANG	"English"
#define ATTENTION "WARNING"
#define DATAMODL "Data template"
#define DATATYPE "Type of data"
#define DECOMPRESSE "uncompressed"
#define ERR232	" erreur num 232 - Cannot find the compression templates table"
#define ERR233	" erreur num 233 - <Compression template> not found in table "
#define ERR234	" error num 234 - Operating mode not checked in the file DataType :"
#define ERR235	" error num 235 <Template of compression> unknown in the file of types of data : "
#define ERR236	" error num 236 when opening file of types of data : "
#define	ERR237	" error num 237: Metadata missing"
#define DIAG237_1	"Identifier of the transmitting centre of the SHIP message"
#define DIAG237_2	"Header numerical indication ii"
#define	ERR238	" error num 238: Error when opening the metadata file"
#define	ERR239	" error num 239: Unexpected operating mode or corrupted binairy file."
#define	ERR240	"MAWSbin error num 240: Arguments problem on command line: Condensed guide display on stderr"
#define	ERR241	" error num 241: Problem when opening the identification table, VOS_ident.txt"
#define	ERR242	" error num 242: The read number in the MEMBER field of the email is not referenced in the table "
#define	ERR243 	" error num 243: Impossible to open the compressed binary file :"
#define	ERR244 	" error num 244: Error when reading the compressed binary file :"
#define	ERR245	" error num 245: Impossible to open the output file"
#define	ERR246	" error num 246: Writing error in the output file."
#define	ERR247	" error num 247: Station in test or dead - no transmission on GTS -"
#define	ERR248	" error num 248: Irretrievable Temporal data "
#define	ERR249	" error num 249: Position not saved: the last position IRIDIUM saved is more recent."
#define	ERR250	" error num 250: Irretrievable Latitude  or longitude or lat and lon not defined"
#define	ERR251	" error num 251: Inaccessible Backup file of the last IRIDIUM position of the ship"
#define	ERR254 	" error num 254: Error when opening the pilot file "
#define	ERR253 	"MAWSbin error num 253: No parameter is accessible on the pilot file "
#define	ERR252	" error num 252: The number of decompressed data oversteps the max expected number "
#define ERRFPL	" error on line num "
#define ERRMETA01 "Cannot open mask file :"
#define ERRMETA02 "Error while processing mask :"
#define ERRMETA03 "WMOid not found in VOSmetada data base!"
#define ERRMETA04 "WMOid not unique in VOSmetada data base"
#define ERRMETA05 "Error while processing mask file in VOSmetada data base."
#define FPILOTE "pilot file"
#define NBOCTLUS "Number of read bytes"
#define NBOCTATT "Number of expected bytes"
#define ERR255	" error num 255: The originating/generating centre is not defined. (see makefile for compilation)"
#define INTROUVABLE	"unobtainable"
#define MODE_OP "Operating Mode"
#define ENTEST "in test"
#define USAGE	"Use :"
#define USAGE1 "CODING GTS MESSAGES MODULE: version"
#define USAGE2 "COMPRESSION/DECOMPRESSION Module: version"
#define USAGE3 "Processing center :" 
#define USAGE4 "-------- Command line parameters : The options in [] are optional.----------"
#define USAGE41 "\t[-i Identification table name in the auxiliary files directory]"
#define USAGE5 "\t[-d fleet identifier(DNID) mandatory for INMARSAT DR]"
#define USAGE6 "\t-n member number (MEMBER) \n\t-f compressed reference file\n\t[-r auxiliary files directory]\n\t[-t reference of an output text file]\n\t[-o ref_file_receiving_MESSAGE]\n\t[-a] writes the MESSAGE in addition\n\t[-l] (display parameters list (value-name))"
#define USAGE61 "\t\t (if option -i is missing, , the identification table is VOS_ident.txt)"
#define USAGE7 "\t\t(if option -r is missing, the auxiliary files are searched in ../data/conf/)"
#define USAGE8 "\t\t(if option -t is missing, the output text is /dev/null)" 
#define USAGE9 "\t\t(if option -o is missing, the MESSAGE is displayed on standard output)"
#define USAGE10 "\t\tThe option -a writes the MESSAGE in addition at the end of the output file.\n\t\t\t(if option -a is missing, the output file is over-writed)"
#define USAGE11 "\tFor IRIDIUM transmissions, the 3 following parameters (recovered in the 'body' of the MAIL)\n\t are mandatory : \n\t\t -e 'Location error in km'\n\t\t -g Longitude \n\t\t -k Latitude \n\t\t"
#define NOSHIPH	" - NO SHIP header - "
#define NOBUOYH	" - NO BUOY header - "
#define NOCENTRE " No centre defined "
#define DATABRUTES "Raw data (without contol)"
#define TIMEOBS "observation date-time"
#define TIMELOC	"localisation date-time"
#define WMOREGION "WMO region number"
#define WMOSSREG "WMO region sub-area"
#define BUOYIDENT "Buoy/platform identifier"
#define N002001 "Type of station"
#define N002038 "Method of sea/water temperature measurement"
#define N002036 "Buoy Type"
#define N004001 "Year"
#define N004002 "Month"
#define N004003 "JDay"
#define N004004 "Hour"
#define N004005 "Minute"
#define N004192 "Date-time"
#define N008021 "Time significance" 
#define N007030 "Height of station ground above mean sea level"
#define N001051 "Platform transmitter ID number"
#define N002148 "Data collection and/or location system"
#define N008081 "Type of equipment"
#define N007062 "Depth below sea surface"
#define N007063 "Depth below sea surface"
#define N007031 "Height of barometer above mean sea level"
#define N007032 "Height of sensor above marine deck platform"
#define N007033 "Height of sensor above mean sea level"
#define N010063 "Characteristic of pressure tendency"
#define N005001 "Latitude (high accuracy)"
#define N006001 "Longitude (high accuracy)"
#define N005002 "Latitude (coarse accuracy)"
#define N006002 "Longitude (coarse accuracy)"
#define N031000 "Delayed descriptor replication factor"
#define N031001 "Delayed descriptor replication factor"
#define N031002 "Delayed descriptor replication factor"
#define N033200 "IRIDIUM CEPradius m"
#define N001196 "Station status"
#define N001197 "MAWSbin ErrorCode"
#define N002168 "HYDROSTATIC PRESSURE OF LOWER END OF CABLE (Pa)"
