#define	LANG	"Francais"
#define ATTENTION "ATTENTION"
#define DATAMODL "Modele de donnees"
#define DATATYPE "Type de donnees"
#define DECOMPRESSE "decompresse"
#define ERR232	" erreur num 232 - On ne trouve pas la table des modeles de compression"
#define ERR233	" erreur num 233 - <Modele de compression> non repertorie dans la table des modeles de compression "
#define ERR234	" erreur num 234 - Mode operatoire non repertorie dans le fichier DataType :"
#define ERR235	" erreur num 235 - <Modele de compression> non repertorie dans fichier des types de donnees : "
#define ERR236	" erreur num 236 - ouverture du fichier des types de donnees : "
#define	ERR237	" erreur num 237: Meta donnee absente (DSO)"
#define DIAG237_1	"Identificateur du centre emetteur du SHIP"
#define DIAG237_2	"Indice numerique ii d'entete"
#define	ERR238	" erreur num 238: Erreur a l'ouverture du fichier de meta donnees (DSI)"
#define	ERR239	" erreur num 239: Mode operatoire inattendu ou fichier binaire corrompu.(DSO)"
#define	ERR240	"MAWSbin erreur num 240: Pb arguments ligne de commande  : Affichage d'un guide condense sur stderr (DSI)"
#define	ERR241	" erreur num 241: PB ouverture de la table d'identification, VOS_ident.txt (DSI)"
#define	ERR242	" erreur num 242: Le numero de membre lu dans le champ MEMBER du mail n'est pas reference dans la table "
#define	ERR243 	" erreur num 243: Impossible d'ouvrir le fichier binaire compresse (DSI) :"
#define	ERR244 	" erreur num 244: Erreur de lecture du fichier binaire compresse (DSO) :"
#define	ERR245	" erreur num 245: Impossible d'ouvrir le fichier de sortie (DSI)"
#define	ERR246	" erreur num 246: Erreur d'ecriture dans le fichier de sortie. (DSI)"
#define	ERR247	" erreur num 247: Station en essai ou morte - pas d'emission sur SMT -"
#define	ERR248	" erreur num 248: Donnee temporelle irrecuperable (DSO)"
#define	ERR249	" erreur num 249: Position de l'observation non sauvegardee : la derniere position IRIDIUM sauvegardee est plus recente."
#define	ERR250	" erreur num 250: Latitude  ou longitude irrecuperable (DSO) ou lat et lon non definies"
#define	ERR251	" erreur num 251: Fichier de sauvegarde de la derniere position IRIDIUM du navire, innaccessible	"
#define	ERR254 	" erreur num 254: Erreur a l'ouverture du fichier pilote (DSI)"
#define	ERR253 	" erreur num 253: Aucun parametre n'est accessible sur fichier pilote (DSO)"
#define	ERR252	" erreur num 252: Le nombre d'elements decompresses depasse le nombre max attendu (DSO)"
#define ERRFPL	" erreur sur ligne num "
#define ERRMETA01 "On ne peut ouvrir le fichier masque : "
#define ERRMETA02 "Erreur dans traitement du masque :"
#define ERRMETA03 "Indicatif OMM introuvable dans la base de donnees VOSmetadata"
#define ERRMETA04 "Indicatif OMM non unique dans la base de donnees VOSmetadata"
#define ERRMETA05 "Pb lors du traitement du fichier de masques de la base de donnees VOSmetadata"
#define FPILOTE "fichier pilote"
#define NBOCTLUS "Nombre d'octets lus"
#define NBOCTATT "Nombre d'octets attendus"
#define	ERR255	" erreur num 255: Le centre d'emission des messages sur le SMT n'est pas defini. (environnement a definir dans le makefile)"
#define INTROUVABLE	"introuvable"
#define MODE_OP "Mode operatoire"
#define ENTEST "en test"
#define USAGE	"Usage :"
#define USAGE1 "MODULE de CODAGE MESSAGES SMT: version" 
#define USAGE2 "MODULE de COMPRESSION/DECOMPRESSION: version"
#define USAGE3 "Centre de traitement :" 
#define USAGE4 "-------- Parametres ligne de commande : Les options entre [] sont optionnelles.----------"
#define USAGE41 "\t[-i nom de la table d'identification qui se trouve dans le repertoire des donnees auxiliaires]"
#define USAGE5 "\t[-d identifiant_de_flotte(DNID) obligatoire pour INMARSAT DR]"
#define USAGE6 "\t-n numero_de_membre(MEMBER) \n\t-f ref_fichier_compresse\n\t[-r repertoire_des_fichiers_auxiliaires]\n\t[-t reference fichier de sortie texte]\n\t[-o ref_fichier_recevant_MESSAGE]\n\t[-a] Ecriture en ajout sur fichier recevant les messages\n\t[-l] (affichage liste parametres (valeur-nom))\n\t[-h] obligatoire si traitement de donnees semi-compressees"
#define USAGE61 "\t\t (en l'absence de l'option -i, la table d'identification est VOS_ident.txt)"
#define USAGE7 "\t\t(en l'absence de l'option -r, les fichiers auxiliaires sont cherches dans ../data/conf/)"
#define USAGE8 "\t\t(en l'absence de l'option -t, la sortie texte va sur /dev/null)"
#define USAGE9 "\t\t(en l'absence de l'option -o, le MESSAGE est affiche sur sortie standard)"
#define USAGE10 "\t\tL'option -a provoque l'ecriture du MESSAGE en ajout a la fin du fichier de sortie\n\t\t\t(en l'absence de l'option -a, le fichier de sortie est ecrase)"
#define USAGE11 "\tPour les transmissions IRIDIUM, les 3 parametres suivants (recuperes dans corps du mail)\n\tsont obligatoires : \n\t\t-e 'Erreur de localisation en km' \n\t\t-g Longitude\n\t\t-k Latitude" 
#define NOSHIPH	" - sans entete SHIP - "
#define NOBUOYH	" - sans entete BUOY - "
#define NOCENTRE " Pas de centre specifie "
#define DATABRUTES "Donnees brutes (sans controle)"
#define TIMEOBS "date-heure observation"
#define TIMELOC	"date-heure localisation"
#define WMOREGION "Region OMM"
#define WMOSSREG "Sous-region OMM"
#define BUOYIDENT "Identificateur de bouee/plateforme"
#define N002001 "Type de station"
#define N002038 "Methode de mesure de la temperature de l'eau/mer"
#define N002036 "Type de bouee"
#define N004001 "Annee"
#define N004002 "Mois"
#define N004003 "Jour"
#define N004004 "Heure"
#define N004005 "Minute"
#define N004192 "Date-heure"
#define N008021 "Caracteristique temporelle"
#define N007030 "Hauteur de la base de la station sur niveau moyen de la mer"
#define N001051 "Numero d'identification de l'emetteur"
#define N002148 "Collecte de donnees et/ou systeme de positoinnement"
#define N008081 "Type d'equipement"
#define N007062 "Profondeur sous la surface de la mer"
#define N007063 "Profondeur sous la surface de la mer"
#define N007031 "Hauteur du barometre sur la surface moyenne de la mer"
#define N007032 "Hauteur du capteur sur le pont du navire"
#define N007033 "Hauteur du capteur sur la surface moyenne de la mer"
#define N010063 "Caracteristique de la tendance baro"
#define N005001 "Latitude (haute precision)"
#define N005002 "Latitude (faible precision)"
#define N006001 "Longitude (haute precision)"
#define N006002 "Longitude (faible precision)"
#define N031000 "Facteur de repetition differee"
#define N031001 "Facteur de repetition differee"
#define N031002 "Facteur de repetition differee"
#define N033200 "Precision localisation IRIDIUM en m"
#define N001196 "Statut de la station"
#define N001197 "Code erreur MAWSbin"
#define N002168 "Pression a l'extremite chaine bathy (Pa avec Pa <- m*10000	)"
